### PR TITLE
Added scale function

### PR DESCRIPTION
**Pull request by hannared**
- added possibility to scale items in the wheel

Example:

Screenshot 2022-11-09 at 22 08 00

### CODE REVIEW

**Comment by erksch** [comment]
Cool addition, thank you! I'll try it out and see if it feels good. 
We would also need to update the README

**Comment by hannared** [comment]
I have updated README as well. Thank you for the great component!:) @erksch

**Review by erksch — APPROVED** [review]

**Comment by erksch** [comment]
Looks good! Thank you very much! I'll add your screenshot to the README as an example.

**Comment by erksch** [comment]
@hannared released your changes in 0.6.0

**Pull request merged**
